spring:
  profiles.active: development

---


spring:
  profiles: development
  application:
     name: ofertasperfildaaas  # Service registers under this name
  datasource:
    url: jdbc:postgresql://localhost:5432/csfpoc
    username: docker
    password: docker
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: ofertas

kafka:
  bootstrap-servers: localhost:9092
  topic:
    posicaocliente: posicaocliente.data.Q
    ofertas: ofertas.data.Q

nearby:
  max:
    radius: 500

server:
  port: 8090