spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: notification
    
kafka:
  bootstrap-servers: localhost:9092
  topic:
    posicaocliente: posicaocliente.data.Q
    ofertas: ofertas.data.Q

server:
  port: 9090